# Generated by Django 4.0.4 on 2022-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_leaderboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(max_length=300),
        ),
    ]
