# Generated by Django 4.0.4 on 2022-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboards',
            name='1C Enterprise',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='ASP.NET',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='C#',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='C++',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='F#',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='HTML+Razor',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='Jupyter Notebook',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='Objective-C',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='Objective-C++',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='OpenEdge ABL',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='Perl 6',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='Protocol Buffer',
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='ASPNET',
            field=models.FloatField(blank=True, default=0, verbose_name='ASP.NET'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='CEnterprise',
            field=models.FloatField(blank=True, default=0, verbose_name='1C Enterprise'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='CSharp',
            field=models.FloatField(blank=True, default=0, verbose_name='C#'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='Cplus',
            field=models.FloatField(blank=True, default=0, verbose_name='C++'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='FSharo',
            field=models.FloatField(blank=True, default=0, verbose_name='F#'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='HTML_Razor',
            field=models.FloatField(blank=True, default=0, verbose_name='HTML+RAZOR'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='JupyterNotebook',
            field=models.FloatField(blank=True, default=0, verbose_name='Jupyter Notebook'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='ObjectiveC',
            field=models.FloatField(blank=True, default=0, verbose_name='Objective-C'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='ObjectiveCplus',
            field=models.FloatField(blank=True, default=0, verbose_name='Objective-C++'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='OpenEdgeABL',
            field=models.FloatField(blank=True, default=0, verbose_name='OpenEdge ABL'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='Perl6',
            field=models.FloatField(blank=True, default=0, verbose_name='Perl 6'),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='ProtocolBuffer',
            field=models.FloatField(blank=True, default=0, verbose_name='Protocol Buffer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
