# Generated by Django 4.0.4 on 2022-06-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_leaderboards_1c enterprise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboards',
            old_name='FSharo',
            new_name='FSharp',
        ),
    ]
