# Generated by Django 4.0.4 on 2022-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_fsharo_leaderboards_fsharp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=150),
        ),
    ]
