# Generated by Django 4.0.4 on 2022-06-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_course_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboards',
            name='yearId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearId',
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='yearID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userYearLevel', to='portfolio.yearlevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yearID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_userYearLevel', to='portfolio.yearlevel'),
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='courseID',
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCourse', to='portfolio.course'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courseID',
        ),
        migrations.AddField(
            model_name='profile',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_Course', to='portfolio.course'),
        ),
    ]
