# Generated by Django 3.2.5 on 2022-06-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_leaderboards_yearid_remove_profile_yearid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearID',
        ),
    ]
