# Generated by Django 4.0.4 on 2022-06-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_ranks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranks',
        ),
        migrations.AddField(
            model_name='profile',
            name='leadB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_leaderboard', to='portfolio.leaderboards'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
